"""empty message

Revision ID: 1701deceb69b
Revises: 
Create Date: 2020-08-23 22:26:15.412294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1701deceb69b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paises',
    sa.Column('pai_id', sa.Integer(), nullable=False),
    sa.Column('pai_nom', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('pai_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paises')
    # ### end Alembic commands ###
